exhibitionsummary/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from . import views
from django.urls import path


app_name = 'exhibitionsummary'
urlpatterns = [
    path('', views.index, name='index'),
    path('conference', views.conference, name='conference'),
    path('conference/<int:pk>/', views.conference_detail, name='conference_detail'),
    path('products', views.products, name='products'),
    path('publications', views.publications, name='publications'),
]

happenings/urls.py
from __future__ import unicode_literals

from django.urls import path
from . import views

app_name='calendar'
urlpatterns = [
    path('', views.EventMonthView.as_view(), name='list'),
    path('month/shift/', views.EventMonthView.as_view(), name='month_shift'),
    path('event-list/shift/', views.EventMonthView.as_view(), name='event_list_shift'),
    path('cal-and-list/shift/', views.EventMonthView.as_view(), name='cal_and_list_shift'),
    path('event/(<pk>[\w-]+)/', views.EventDetailView.as_view(), name='detail'),
    path('(<year>\d{4})/(<month>\d{2}|\d{1})/', views.EventMonthView.as_view(), name='list'),
    path('(<year>\d{4})/(<month>\d{2}|\d{1})/(<day>\d{2}|\d{1})/', views.EventDayView.as_view(), name='day_list'),
]

sd/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exhibitionsummary.urls')),
    path('', include('products.urls')),
    path('calendar/', include('happenings.urls')),
]

exhibitionsummary/models.py
from django.db import models


# Create your models here.



class Summary(models.Model):

	conference = models.CharField(max_length=200)

	website = models.URLField(max_length=300, blank=True)

	contact = models.EmailField(max_length=300, blank=True)

	venue = models.CharField(max_length=300, blank=True)

	start = models.DateField('Start date', null=True)

	end = models.DateField('End date', null=True)

	accommodation = models.CharField('Accomodation address', max_length=300, blank=True)

	setup = models.DateTimeField('Set up', blank=True, null=True)

	dismantle = models.DateTimeField('Dismantle', blank=True, null=True)

	booth = models.IntegerField('Booth #', blank=True, default=1)

	furniture = models.TextField('Furniture provided', max_length=300, blank=True)

	registrations = models.IntegerField('Complimentary registrations', blank=True, default=1)

	power = models.BooleanField('Power supplied', default=False)

	brochures = models.TextField('Brochures', default="QTY x BROCHURE #", help_text="Include qty", max_length=500, blank=True)

	equipment = models.TextField('Equipment', default="", max_length=500, blank=True)

	banners = models.TextField('Banners', default="", max_length=200, blank=True)

	delivery = models.BooleanField('Delivered', default=False)

	hand = models.BooleanField('Hand carried', default=False)

	address = models.CharField('Delivery address', default="", max_length=300, blank=True)

	date = models.DateField('Ship date', help_text="2-3 days for Brisbane/Sydney/Adelaide/Melbourne, otherwise 4-5 days", null=True, blank=True)

	details = models.TextField('Details', default="", help_text="Artwork required, important links etc.", max_length=400, blank=True)

	class Meta:
		verbose_name = 'Exhibition Summary'
		verbose_name_plural = 'Exhibition Summaries'
		ordering = ['start']



	def get_absolute_url(self):
		return reverse('exhib-summary', args=[str(self.id)])

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.conference


	@property
	def Summary(self):
		return '%s - present' % self.setup.strftime('%d/%m/%Y')

exhibitionsummary/views.py
from django.shortcuts import render, render_to_response
from django.utils import timezone
from .models import Summary
from happenings.models import Event
from products.models import Product, Publication
from django.shortcuts import render, get_object_or_404

# Create your views here.

def index(request):
    summaries = Summary.objects.order_by('conference')
    return render(request, 'index.html', {'summaries': summaries})

def conference(request):
    conference = Summary.objects.order_by('start')
    return render(request, 'conference.html', {'conference': conference})

def conference_detail(request, pk):
    summaries = Summary.objects.order_by('conference')
    conference = get_object_or_404(Summary, pk=pk)
    return render(request, 'exhibitionsummary/conference_detail.html', {'conference': conference}, {'summaries': summaries})

def sidebar(request):
    sidebar = Summary.objects.all()('start')
    return render(request, 'base.html', {'sidebar': sidebar}, context_instance=RequestContext(request))

def products(request):
    products = Product.objects.order_by('company')
    return render(request, 'products.html', {'products' : products})

def calendar(request):
    return render(request, 'exhibitionsummary/calendar.html')

def conferenceindex(request):
    conference = Summary.objects.order_by('start')
    return render(request, 'index.html', {'conferenceindex': conferenceindex})

def publications(request):
    publications = Publication.objects.order_by('date')
    return render(request, 'publications.html', {'publications': publications})

exhibitionsummary/templates/exhibitionsummary/base.html
{% load static %}
<html>
<title>Symbiotic Devices / Admin</title>
<head>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
	<link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans|Ubuntu" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'happenings/css/calendar.css' %}">
	{% block extra_css %}{% endblock extra_css %}
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
</head>
<body>
	<div class="dashboard">
		<nav>
			<a href="{% url 'exhibitionsummary:index' %}"><img src="{% static 'img/white.png' %}" id='logo'></a>
			<div class="nav">
				<p>MAIN</p>
				<a href="{% url 'exhibitionsummary:index' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
				<!--<a href="{% url 'calendar:list' %}"><i class="fas fa-calendar-alt"></i>Events</a>!-->
				<a href="#" id="drop1"><i class="fas fa-list-ul"></i>Exhibition Summaries</a>
			    	<div class="drop2">
			    		<a href="{% url 'exhibitionsummary:conference_detail' pk=sidebar.0.id %}">{{ sidebar.0.conference }}</a>
			    		<a href="{% url 'exhibitionsummary:conference_detail' pk=sidebar.1.id %}">{{ sidebar.1.conference }}</a>
			    		<a href="{% url 'exhibitionsummary:conference' %}">View all</a>
			    	</div>
				<a href="{% url 'exhibitionsummary:products' %}"><i class="fas fa-suitcase"></i>Products</a>
				<a href="{% url 'exhibitionsummary:publications' %}"><i class="fas fa-file-alt"></i>Publications</a>
			</div>
			<div class="activity">
				<p>RECENT ACTIVITY</p>
			</div>
		</nav>
		<div class="body">
			<div class="strip">
				<a href="{% url 'exhibitionsummary:index' %}"><img src="{% static 'img/white.png' %}" id='logomobile'></a>
				<div class="tree">
					{% block index_tree %}
					{% endblock %}
					{% block conference_tree %}
					{% endblock %}
					{% block conference_tree1 %}
					{% endblock %}
					{% block product_tree %}
					{% endblock %}
					{% block calendar_tree %}
					{% endblock %}
					{% block publications_tree %}
					{% endblock %}
				</div>
				<div class="user">
					<a href="{% url 'admin:index' %}">{% if user.is_authenticated %}
																    {{ user.username }}
																{% else %}
																    Log in.
																{% endif %}</a>
					<br>{% now "SHORT_DATETIME_FORMAT" %}
				</div>
			</div>
			<div class="content">
				<div class="rollout"><div class="iconrotate"><i class="fas fa-angle-left"></i></div></div>
				{% block index %}
				{% endblock %}
				{% block product_table %}
				{% endblock %}
				{% block details %}
				{% endblock %}
				{% block conference %}
				{% endblock %}
				{% block publications_table %}
				{% endblock %}
				{% block content %}
				{% endblock content %}
				<script src="{% static 'happenings/js/calendar.js' %}"></script>
				{% block extra_js %}{% endblock extra_js %}
			</div>
			<div class="version"> Symbiotic Devices admin v1.1.2</div>
	</div>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'js/js.js' %}"></script>
	<script>
	(function(w,d,s,g,js,fs){
	  g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(f){this.q.push(f);}};
	  js=d.createElement(s);fs=d.getElementsByTagName(s)[0];
	  js.src='https://apis.google.com/js/platform.js';
	  fs.parentNode.insertBefore(js,fs);js.onload=function(){g.load('analytics');};
	}(window,document,'script'));
	</script>
<script>
gapi.analytics.ready(function() {
  gapi.analytics.auth.authorize({
    container: 'embed-api-auth-container',
    clientid: '260680418718-rqiue7vu7jpvhf217oeac57l5s6s4vqj.apps.googleusercontent.com'
  });
  var dataChart1 = new gapi.analytics.googleCharts.DataChart({
    query: {
			'ids': 'ga:188338612',
      metrics: 'ga:sessions',
      dimensions: 'ga:country',
      'start-date': '30daysAgo',
      'end-date': 'today',
      sort: '-ga:sessions'
    },
    chart: {
      container: 'geochartcontainer',
      type: 'GEO',
      options: {
        'width': '500',
				'backgroundColor': 'transparent',
				'color': '#D8F050',
      }
    }
  });
	dataChart1.execute();

  var dataChart2 = new gapi.analytics.googleCharts.DataChart({
    query: {
			'ids': 'ga:188338612',
      metrics: 'ga:sessions',
      dimensions: 'ga:date',
      'start-date': '30daysAgo',
      'end-date': 'today',
    },
    chart: {
      container: 'chart-2-container',
      type: 'COLUMN',
			options : {
				'width': '500',
				'backgroundColor': 'transparent',
				'colors': ['#d7e153', '#Fc4550', '#A31621', '#BEDBE7'],
					}
    }
  });
	dataChart2.execute();

	var dataChart3 = new gapi.analytics.googleCharts.DataChart({
	  query: {
	    'ids': 'ga:188338612',
			dimensions: 'ga:pagePath',
			'end-date': 'today',
			metrics: 'ga:pageviews,ga:entrances',
			sort: 'ga:pageviews'
	  },
	chart: {
    container: 'chart-3-container',
    type: 'TABLE',
		options: {
			'width': '100%',
			'backgroundColor': 'transparent',
			sortColumn: 1,
			sortAscending: false,
			}
  	}
	});
	dataChart3.execute();

	var dataChart4 = new gapi.analytics.googleCharts.DataChart({
	  query: {
	    'ids': 'ga:188338612',
	    metrics: 'ga:sessions',
	    dimensions: 'ga:city',
			'end-date': 'today',
			filters: 'ga:country==Australia,ga:country==New Zealand',

	  },
	chart: {
    container: 'chart-4-container',
    type: 'PIE',
		options : {
			'backgroundColor': 'transparent',
			'is3D': true,
			'width': '500',
			'colors': ['#d7e153', '#FDD31D', '#Fc4550', '#A31621', '#BEDBE7']
			}
  	}
	});
	dataChart4.execute();
	});
</script>
	{% block javascript %}{% endblock %}
</body>
</html>

exhibitionsummary/templates/exhibitionsummary/conference_detail.html
{% extends 'exhibitionsummary/base.html' %}
{% block details %}
<div class="conference_detail">
        <div class="main_detail">
          <a href="{{ conference.website }}"<h1>{{ conference.conference }}</h1></a>
          <h3>{{ conference.venue }}</h3>
          <p>{{ conference.start }} - {{ conference.end }}</p>
          <p>{{ conference.contact }}</p>
        </div>
        <div class="conference_countdown">
          <h1>{{ conference.start|timeuntil }}</h1>
        </div>
        <div class="conference_booth">
          <div class="header2">Booth</div>
          <div class="conference_booth-body">
          <h5>Number:</h5> {{ conference.booth }}<br>
          <h5>Setup:</h5> {{ conference.setup }}<br>
          <h5>Dismantle:</h5> {{conference.dismantle }}<br>
          <h5>Furniture:</h5> {{conference.furniture|linebreaksbr }}
          <h5>Power:</h5> {{ conference.power }}
          </div>
        </div>
        <div class="conference_equipment">
          <div class="header2">Equipment</div>
          <div class="conference_equipment-body">
          <h5>Brochures:</h5> {{ conference.brochures|linebreaksbr }}<br>
          <h5>Equipment:</h5> {{ conference.equipment|linebreaksbr }}<br>
          <h5>Banners:</h5> {{ conference.banners|linebreaksbr }}<br>
          </div>
        </div>
        <div class="conference_details">
          <div class="header2">Details</div>
          <div class="conference_details-body">
          <h5>Complimentary Registrations:</h5> {{ conference.registrations }}<br>
          <h5>Notes</h5> {{ conference.details|linebreaksbr }}
          <h5>Shipping address:</h5> {{conference.address }}<br>
          <h5>Shipping date:</h5> {{conference.date }}
          </div>
        </div>
</div>
{% endblock %}
{% block conference_tree %}
<a href="{% url 'exhibitionsummary:index' %}">Dashboard</a> > <a href="{% url 'exhibitionsummary:conference' %}">Exhibition Summaries</a> > {{ conference.conference }}
{% endblock %}

exhibitionsummary/templates/exhibitionsummary/post_list.html
<html>
<body>
<div>
    <h1><a href="/">Symbiotic Devices</a></h1>
</div>

{% for post in posts %}
    <div>
        <p>published: {{ post.date}}</p>
        <h2><a href="">{{ post.conference }}</a></h2>
        <p>{{ post.summary|linebreaksbr }}</p>
    </div>
{% endfor %}



{{ post.conference }}

<p> fck u </p>
</body>
</html>

exhibitionsummary/templates/exhibitionsummary/summary_list.html
{% extends 'exhibitionsummary/base.html' %}

{% block content %}
	{% for summaries in summaries %}
	    <div>
	        <h3><a href="{% url 'exhibitionsummary:conference_detail' pk=summaries.id %}">{{ summaries.conference}}</a></h3>
	        <p>{{ summaries.start }} - {{ summaries.end }}</p>
	        <p>{{ summaries.venue }}</p>
	    </div>
	{% endfor %}
{% endblock %}